### ISSUE TITLE
Add a Contribute Link

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound.github.io#2]
Add a Contribute link and page that explains ways users and developers can contribute, as well as pointers on how to do so. For example, things we may want to cover are "Submitting a bug", "Submitting a feature request", "Correcting a manual entry", "contribute code", etc.  We can then point to using the issue tracker with some guidance on what to do, or ask for pull-requests and how to do that, etc.

**Comment by oscii** [comment]
Another one of #42
