### ISSUE TITLE
Reorganize download section

### ISSUE THREAD

**Issue by oscii** [csound/csound.github.io#27]
Hi all!

I'd like to put down some ideas based on what we've discussed at the round table. The key topic of the discussion was reorganizing the web site to make it more accessible to newbies. One of the points made in the speech was that often users think that CsoundQt is Csound… But this may be just a consequence of the problem and not the problem itself. The thing is that we have several type of users and we ship one package for everyone. Maybe you guys can better categorize users as you have Csound teaching experience, but I'd like to speculate on this topic too. So I tried to categorize the users by answering the following questions:

1. What do users do? Who are the users?
2. What are the level of the user?
3. Why hypothetically have they choose Csound?
4. What is their workflow?
5. What features are important for them?
6. What software package could be suitable for their workflow?

- DSP coders / scientists
  1. Design audio processing algorithms, sound-related research.
  2. These users are (probably) have some theoretical knowledge of the sound and have concrete tasks or clear goals.
  3. You can do low-level per-sample calculation in Csound, OS-specific audio i/o abstractions, ready-made primitives for the DSP stuff development (for example, there are waveguide opcodes that could be used in reverb design).
  4. Probably a lot of coefficient tuning, a lot of orchestra reloading, a lot of data plotting, etc…
  5. Solid visualization tools (frequency/phase response, oscilloscope, etc.), ability to work with data and analyze it.
  6. CsoundQt, icsound.
- Musicians / sound designers
  1. Explore sonic spaces, make new sounds
  2. The level of the users can vary highly—from complete newbie to DSP-guru. Most of such activities doesn't have a clear goal or concrete tasks.
  3. Csound has opcodes for (almost) every sound synthesis/processing method, and hence it's sonic capabilities are unlimited. Csound has very simple and readable syntax (comparing, for example, to SuperCollider), relatively easy to get into.
  4. Most of sound or music enthusiasts and professionals probably developed their own work habits, set of tools, etc. So Csound should be embedded to their work process. Most of these people are working in DAWs, so they're forced to go back and forth between softwares.
  5. Integration with their tools, GUI with knobs and switches, ability to make things quickly, a bunch of ready-made stuff available for experiments.
  6. Csound as VST — together with @rorywalsh we've made a prototype of Csound editor in Cabbage, which allows to edit `.csd` right in VST. It worked, but they were bugs. `csound~` and `csoundapi~` are also fall in this category.
- Interactive stuff makers
…

OK, we can continue to add another use cases, but now it's too late and my brain declined to provide more.

What I think:
- We can create several Csound distributions (no more than 3 or it'd be confusing), and provide an explanation on what audience it's attended to. At least Sound Design and Scientific packages are sounds good.
- It may be worth it to develop existing tools with target audience in mind and not do one-for-everything tools.

**Comment by vlazzarini** [comment]
These ideas are worth exploring. However we would need more support from the community for these, as there are only four of us producing releases at the moment. We simply do not have the numbers in the team to create and test a larger variety of packages for three or more operating systems.

**Comment by rorywalsh** [comment]
These are interesting points, and I can see how a "Csound notebook" distro
might be an attractive option for the more scientifically inclined. But I
think that maintaining so many different distributions would be tricky. It
might be enough to feature a section on the site with information about the
different uses of Csound, and suggestions about the appropriate editors and
frontends that might prove useful.

**Comment by unriginal** [comment]
I think having a page specifically for beginners that points to or
recommends QT, as well as containing links for the latest Csound distro and
the manual and Floss manual might be helpful. I think having a page that
describes different frontends and what they're typically used for is
useful, but if I'm a beginner and I want to get started with something
simple and without making a lot of decisions, I'm more interested in
downloading a package of software that I can start using immediately,
rather than having to make a choice about what frontend to use.

**Comment by oscii** [comment]
Thanks for the points. Maybe I shouldn't have used the word “distribution”. My idea was that on the downloads we can simply say something like:

1. If you want to do DSP science stuff, then go to CsoundQt download page or point to the icsound setup instructions.
2. If you'd like to use Csound in your DAW, then download Cabbage.
3. If you are a beginner (or learner), just try Csound online, go to interactive learning lessons or listen to the opcode examples in your browser.

Anyway, Csound is a multifaceted thing and clearly stating what (and how) user can do something would be useful. And generally, stating explicitly what you can actually do with Csound would be great. Even better if we point there on examples and where to find additional info.

**Comment by unriginal** [comment]
Ahhhh I was thinking the opposite- having a page that describes each front-end, as well as a separate Beginners or Getting Started page with more in depth info target at beginners, and that each of those ones would link to downloads where appropriate.

**Comment by joachimheintz** [comment]
currently we have this:
http://csound.github.io/frontends.html

if you have additions / corrections, please write them down and send it 
either to a list or to one of us off-list.

thanks -
	joachim
