### ISSUE TITLE
add download icons with direct links to installers

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound.github.io#30]
Users shouldn't have to navigate to sourceforge to find an installer.

**Comment by oscii** [comment]
I remember we planned to move binaries to bintray.com. Any progress on that?

**Comment by rorywalsh** [comment]
I'm not sure what the final thoughts on this are. I guess it's down to the
devs. I had proposed making releases on github, but it turns out the
statistical information on releases is pretty limited compared after all.

**Comment by kunstmusik** [comment]
I think we may move to github for releases.  The links I put in for now
should be okay; we can update the links after the release.

**Comment by kunstmusik** [comment]
I think we should be able to grab free icons for each operating system here:

http://www.iconarchive.com/search?q=apple

**Comment by oscii** [comment]
http://csound.github.io/download.html
