### ISSUE TITLE
Add image on the about.html page

### ISSUE THREAD

**Issue by oscii** [csound/csound.github.io#34]

**Comment by jpffitch** [comment]
What image?

**Comment by oscii** [comment]
A fancy image with Csound code, UI or something like that. Just to make the page less text-heavy. Any ideas what could it be?

**Comment by rorywalsh** [comment]
I think it's Ok, but if you find something suitable I don't see why not.

**Comment by oscii** [comment]
Ok, got one from csounds.com.
