### ISSUE TITLE
Add contribute.html page

### ISSUE THREAD

**Issue by oscii** [csound/csound.github.io#39]

**Comment by oscii** [comment]
@rorywalsh @kunstmusik @berntisak 
Hi everyone!
Did we have information about how to contribute to Csound on the old web site. Particularly, we need the following info:

1. How to involve in the Csound development.
2. How to submit a project to the “Projects” section.
3. How to add a track made with Csound to the “Music by Csounders” section.

**Comment by jpffitch** [comment]
see issue #2.  these should be amalgamated
