### ISSUE TITLE
Fill out contribute.md page

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound.github.io#42]
I have added a skeleton contribute.md page with headings. We need to fill out the sections with information.

**Comment by oscii** [comment]
Who will write instructions, etc.&

**Comment by berntisak** [comment]
Made some changes to the structure. I can write a suggestion for the Community section. I guess the devs should discuss how they want help from people for that section?

I think we should have another name than "Documentation" though - something that covers everything from reference & FLOSS manuals to Csound journal articles, tutorials, interactive learning and youtube videos

**Comment by joachimheintz** [comment]
although the contribute page is not at all perfect, i close this issue as there are other pages on csound.com which need similar improvements.
