### ISSUE TITLE
Add News Story for ICSC 2015 Proceedings

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound.github.io#46]
https://zenodo.org/collection/user-icsc2015

**Comment by oscii** [comment]
There is already a story in the Csound Journal: http://csoundjournal.com/issue22/ICSC2015Report.html
Do you propose to repost it or create a more concise material with references to videos, photos, etc.?

**Comment by kunstmusik** [comment]
I think just a short post to announce it is available and a link to the
Journal issue would do.

**Comment by oscii** [comment]
http://csound.github.io/site/news/2016/05/12/icsc2015-materials
