### ISSUE TITLE
Broken links to FLOSS manual 

### ISSUE THREAD

**Issue by jtbeckha** [csound/csound.github.io#61]
Based on a quick grep for "FLOSS" through the codebase it looks like there are a number of broken links to the FLOSS manual
E.g. http://write.flossmanuals.net/csound/the-csound-api/ -> http://write.flossmanuals.net/csound/a-the-csound-api/

http://write.flossmanuals.net/csound/index/ -> http://write.flossmanuals.net/csound/preface/

**Comment by joachimheintz** [comment]
thanks, i will look at it.

**Comment by joachimheintz** [comment]
i think i have fixed the broken links.  please check and re-open (if possible with the files and lines) if there is anything left.
