### ISSUE TITLE
Audio rate `expsegr` opcode is affected by control rate.

### ISSUE THREAD

**Issue by IronAttorney** [csound/csound.github.io#76]
[MINIMUM_BUG_EXAMPLE.csd.zip](https://github.com/csound/csound.github.io/files/4899222/MINIMUM_BUG_EXAMPLE.csd.zip)

When using the audio rate `expsegr` opcode, (specifically the version of `expseg `with the release segment),  the results are impacted by the control rate.

Attached is a minimal example in which I have one instrument using `expsegr`, and a different version of the same instrument using the non release version `expseg` commented out so they can be quickly switched between for testing. With the first instrument, ksmps up to around 96 produce audio, but the audio varies with the ksmps value. For ksmps > 96, there is silence (I think the first trigger has infinite amplitude and I guess the rest are silenced). The second version is unaffected by the value of ksmps.

I believe `linesegr` works as expected.

**Comment by vlazzarini** [comment]
closing this here as it is the wrong place. Moved to the csound issues, https://github.com/csound/csound/issues/1358
