### ISSUE TITLE
Please add ModulysCS to related projects

### ISSUE THREAD

**Issue by NSDopen** [csound/csound.github.io#80]
Hello,

ModulysCS is build around ModulysVst which is a giant step-sequencer/phrase generator in Vst-plugin format.
ModulysCS is a portable app for Windows (15MB zip-file) and includes a Csound CSD-editor.

You can create your own presets and instruments.
It uses Csound 6.15.0 api for communication and sound generation.

It's totally free without restrictions.

For more info
www.raxntrax.com
www.raxntrax.com/modulys/modulyscs

Thanks in advance!

**Comment by NSDopen** [comment]
Is somebody still reading this issue tracker?

**Comment by rorywalsh** [comment]
I just posted it now to the latest post section. I think people were just waiting for someone else to do it 😆

**Comment by joachimheintz** [comment]
i think you forgot the header in the .md file, so it is not visible.  i 
can do it, but i am wondering: was the suggestion not to put it in
https://csound.com/projects.html ?

(i can do it as well =)

**Comment by kunstmusik** [comment]
I fixed the post, but I agree it should be added to projects page too.

**Comment by joachimheintz** [comment]
done =)
