### ISSUE TITLE
Bitwise logical operators

### ISSUE THREAD

**Issue by ncg777** [csound/csound.github.io#86]
Bitwise logical operators (&, |...) would be really useful both in score and orchestra. 

Hexadecimal numbers inherently determine binary strings which can be used as rhythms.

**Comment by jpffitch** [comment]
Sorry but what do you want?  Bitwise logic is in the orc.  Do you just want tin score?

**Comment by ncg777** [comment]
Bitwise logic is available in the orchestra? I could not find it in the documentation. I guess its the usual & and | ?

In fact, I would just need it in the orch, so in that case, it's already done...

Thanks!

**Comment by kunstmusik** [comment]
I used bitwise operators frequently with hex and live coding, so they're definitely there. You can search for "bitwise" on the manual and you'll see the entries: https://csound.com/docs/manual/

Closing out this issue.

**Comment by ncg777** [comment]
Gosh... Why haven't I seen that..

Sorry for asking.
