### ISSUE TITLE
Suggest to add in ide.csound.com for quickstart examples

### ISSUE THREAD

**Issue by joshkopecek** [csound/csound.github.io#87]
Since https://ide.csound.com is such a great resource and quick way to get started with csound, can I suggest the examples on the main page are embedded from there, much in the same way as interactive examples from codepen?

Or at least provide links to the examples that you can just click, play, and edit?

**Comment by joshkopecek** [comment]
I just created a PR for this

**Comment by vlazzarini** [comment]
thanks, I'll close this now.
