### ISSUE TITLE
WinXound link seems to be broken

### ISSUE THREAD

**Issue by mgrovely** [csound/csound.github.io#89]
The new site appears to be [here](https://mnt.conts.it/winxound/).

**Comment by vlazzarini** [comment]
We don't have a web maintainer/editor at the moment, so a PR could be a way to fix this.

**Comment by joachimheintz** [comment]
but the binaries to download are from 2015 ...
do you really think we should link to them?  on which OS version does it 
work for you?
(of course it is in each case better than a broken link ...)

**Comment by joachimheintz** [comment]
all links seem to be broken, and i am afraid that we must remove WinXsound from the list of frontends.
i close this now and ask the list; if the result remains the same, i will remove it from the site.
