### ISSUE TITLE
32bit limitation in bitwise logic opcodes, except | (or)

### ISSUE THREAD

**Issue by janahuebenthal** [csound/csound.github.io#93]
I ran into oddities while using bitwise logic with huge numbers.  They are not working as expected on 64bit Csound.

You will find a boiled down version of my analysis in the attached csd (renamed to *.txt due to file type limits).
[bitwise.txt](https://github.com/csound/csound.github.io/files/10812069/bitwise.txt)

Tested with Csound 6.17 in Ubuntu and Win10.

Cheers, Jana

**Comment by vlazzarini** [comment]
Thanks for this. We'll investigate.  It's likely that we are using 32bit ints. 
We may be able to change this for Csound 7.

**Comment by vlazzarini** [comment]
Yes, they are using 32bit ints, rounded from MYFLT. I also found out two things

- they are not in the core set of opcodes (OOps/aops.c is where I would expect them), but in Opcodes/ugmoss.c
- the manual example is broken on Csound 7 (develop branch), which may either be a parser3 issue (?)

So we should make these using 64bit ints when MYFLT is double (is that right @jpffitch ?)

**Comment by vlazzarini** [comment]
The issue with the manual example is precedence. 

```
if (ipp & ivalue >= ivalue)
```
in Csound 6.x  is `if ((ipp & ivalue) >= ivalue)`  but it seems to be `if (ipp & (ivalue >= ivalue))` in Csound 7 causing the code to fail to compile. What do you reckon, @kunstmusik ?

**Comment by vlazzarini** [comment]
done on develop branch
